dist: xenial
language: python
python:
  - "3.7"

branches:
  only:
  - master

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels bioconda
  - conda install conda-build conda-verify cython numpy
  - conda info -a
  - conda build . --numpy 1.15 --python 3.7 -c bioconda
  - conda install ms2pip --use-local -c bioconda

script:
  - ms2pip -h
