{% set data = load_setup_py_data() %}

package:
  name: ms2pip
  version: {{ data.get('version') }}

#source:
#  url: https://github.com/compomics/ms2pip_c/archive/{{ data.get('version') }}.tar.gz
#  md5: d6c769ec68a18d9b6d626d8e9e416c2e
source:
path: ./

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --ignore-installed -vv"
  entry_points:
    - ms2pip=ms2pip.__main__:main
    - fasta2speclib=fasta2speclib.fasta2speclib:main

requirements:
  build:
    - python >=3.6,<4
    - numpy >=1.15,<2
    - Cython >=0.29.2,<1
  host:
    - python >=3.6,<4
    - numpy >=1.15,<2
    - Cython >=0.29.2,<1
  run:
    - python >=3.6,<4
    - numpy >=1.15,<2
    - Cython >=0.29.2,<1
    - pandas >=0.23.4,<1
    - scipy >=1.1.0,<2
    - matplotlib >=3.0.2,<4
    - pyteomics >=4.1.2,<5
    - biopython >=1.72,<2

#test:
#  commands:
#    - python setup.py test

about:
  home: "{{ data.get('url') }}"
  license: APACHE
  license_file: LICENSE
  summary: "{{ data.get('description') }}"

extra:
  identifiers:
    - doi:10.1093/nar/gkz299
    - doi:10.1093/nar/gkv542
    - doi:10.1093/bioinformatics/btt544